### ISSUE TITLE
chore(deps): Duplicate identifier errors on angular2-webpack-starter app

### ISSUE THREAD

**Issue by lanocturne** [valor-software/ng2-dragula#62]
If I import ng2-dragula: 
`import {DragulaService} from "ng2-dragula/ng2-dragula";`
`import {Dragula} from "ng2-dragula/ng2-dragula";`
TS compiler complains a dozen of such errors on my stater app
ERROR in /ui/node_modules/ng2-dragula/node_modules/angular2/typings/node/node.d.ts
(44,5): error TS2300: Duplicate identifier 'cache'.

'dragula' is required. Any insights would be much appreciated.

**Comment by valorkin** [comment]
* change dependencies to peerDependencies

**Comment by mburger81** [comment]
Same problem for me, peerDependencies didn't resolve the problem for me.

thx

**Comment by valorkin** [comment]
ok, there are several things to check
but in general I have an idea where root problem is
for now can you try to 
use npm@latest
delete node_modules and reinstall?

**Comment by denodaeus** [comment]
Also tried moving stuff to peerDependencies in the package.json for ng2-dragula (specifically angular and zone), didn't work for me either.

**Comment by mburger81** [comment]
@valorkin my npm version is 3.3.12, tried to delete node_modules and reinstall, it doesn' work

**Comment by denodaeus** [comment]
@valorkin Tried with the below npm version, encountering the same problem:

➜  ~  npm -v
3.3.12

**Comment by valorkin** [comment]
guys I just published a `beta` version
so do this
```bash
npm i dragula ng2-dragula --save
typings install dragula --ambient --save
```

and you are trying to use it from system.js?

so check this guide: https://github.com/valor-software/ng2-bootstrap#quick-start
especially about map for moment.js
you will have to map
```
map: {
      moment: 'node_modules/dragula/dist/dragula.js'
    }
```

please try and update me about this

**Comment by denodaeus** [comment]
➜  test-ui git:(master) ✗ npm install --save dragula ng2-dragula@beta
├── UNMET PEER DEPENDENCY bootstrap@3.3.6
├── dragula@3.6.6
├── UNMET DEPENDENCY es6-promise@3.0.2
├── ng2-dragula@1.0.5
├── UNMET DEPENDENCY reflect-metadata@0.1.2
├── UNMET DEPENDENCY rxjs@5.0.0-beta.0
└── UNMET PEER DEPENDENCY zone.js@0.5.11

npm WARN EPEERINVALID angular2@2.0.0-beta.3 requires a peer of es6-promise@^3.0.2 but none was installed.
npm WARN EPEERINVALID angular2@2.0.0-beta.3 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN EPEERINVALID angular2@2.0.0-beta.3 requires a peer of rxjs@5.0.0-beta.0 but none was installed.
npm WARN EPEERINVALID ng2-dragula@1.0.5 requires a peer of bootstrap@3.3.6 but none was installed.
npm WARN EPEERINVALID ng2-dragula@1.0.5 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN EPEERINVALID ng2-dragula@1.0.5 requires a peer of rxjs@5.0.0-beta.0 but none was installed.
npm WARN EPEERINVALID ng2-dragula@1.0.5 requires a peer of zone.js@0.5.10 but none was installed.

**Comment by denodaeus** [comment]
The thing is, npm3 doesn't install peer dependencies anymore.  Are you using npm3?

**Comment by denodaeus** [comment]
Also, I tried to work around this by going to my node_modules directory and git cloning your upgrade-to-g2-0beta-3 branch, and updating the package.json to require zone.s@^0.5.11.  After that when I do an npm install, I get the following errors (note:  I also did a typings install first seeing that you converted to using typings and there's a typings.json here):

```shell
➜  ng2-dragula git:(upgrade-to-ng2-0beta-3) ✗ npm install

> ng2-dragula@1.0.5 prepublish /Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/ng2-dragula
> tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions && gulp postinstall


-> running reinstall

>> written zero files

   >> definition-header (node)
   >> reflect-metadata (node)
   >> tslint (node)

>> nothing rebundled
[23:37:48] Requiring external module ts-node/register
----------------------------------
⨯ Unable to compile TypeScript

gulpfile.ts (15,26): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (22,24): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (33,25): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (48,30): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (53,31): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (60,19): Parameter 'done' implicitly has an 'any' type. (7006)
gulpfile.ts (69,20): Parameter 'done' implicitly has an 'any' type. (7006)
tools/config.ts (2,20): Cannot find module 'yargs'. (2307)
tools/utils.ts (7,29): Parameter 'plugins' implicitly has an 'any' type. (7006)
tools/utils/code_change_tools.ts (2,36): Cannot find module 'connect-livereload'. (2307)
tools/utils/code_change_tools.ts (4,31): Cannot find module 'angular2-hot-loader'. (2307)
tools/utils/code_change_tools.ts (5,27): Cannot find module 'tiny-lr'. (2307)
tools/utils/code_change_tools.ts (19,15): Parameter 'files' implicitly has an 'any' type. (7006)
tools/utils/code_change_tools.ts (35,4): Parameter 'req' implicitly has an 'any' type. (7006)
tools/utils/code_change_tools.ts (35,9): Parameter 'res' implicitly has an 'any' type. (7006)
tools/utils/code_change_tools.ts (35,14): Parameter 'next' implicitly has an 'any' type. (7006)
tools/utils/server.ts (2,31): Cannot find module 'open'. (2307)
tools/utils/server.ts (18,34): Parameter 'e' implicitly has an 'any' type. (7006)
tools/utils/tasks_tools.ts (4,34): Cannot find module 'gulp-load-plugins'. (2307)
tools/utils/tasks_tools.ts (5,31): Cannot find module 'run-sequence'. (2307)
tools/utils/tasks_tools.ts (23,7): Variable 'tasks' implicitly has an 'any[]' type. (7005)
tools/utils/tasks_tools.ts (49,17): Parameter 'path' implicitly has an 'any' type. (7006)
tools/utils/template_injectables.ts (1,24): Cannot find module 'slash'. (2307)
tools/utils/template_injectables.ts (19,31): Parameter 'plugins' implicitly has an 'any' type. (7006)
tools/utils/template_injectables.ts (19,40): Parameter 'env' implicitly has an 'any' type. (7006)
tools/utils/template_injectables.ts (20,20): Parameter 'filepath' implicitly has an 'any' type. (7006)
typings/browser/ambient/dragula/dragula.d.ts (10,9): Duplicate identifier 'containers'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (11,9): Duplicate identifier 'isContainer'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (12,9): Duplicate identifier 'moves'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (13,9): Duplicate identifier 'accepts'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (14,9): Duplicate identifier 'invalid'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (15,9): Duplicate identifier 'direction'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (16,9): Duplicate identifier 'copy'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (17,9): Duplicate identifier 'revertOnSpill'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (18,9): Duplicate identifier 'removeOnSpill'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (19,9): Duplicate identifier 'delay'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (20,9): Duplicate identifier 'mirrorContainer'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (24,9): Duplicate identifier 'containers'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (25,9): Duplicate identifier 'dragging'. (2300)
typings/browser/ambient/dragula/dragula.d.ts (47,5): Duplicate identifier 'export='. (2300)
typings/main/ambient/dragula/dragula.d.ts (10,9): Duplicate identifier 'containers'. (2300)
typings/main/ambient/dragula/dragula.d.ts (11,9): Duplicate identifier 'isContainer'. (2300)
typings/main/ambient/dragula/dragula.d.ts (12,9): Duplicate identifier 'moves'. (2300)
typings/main/ambient/dragula/dragula.d.ts (13,9): Duplicate identifier 'accepts'. (2300)
typings/main/ambient/dragula/dragula.d.ts (14,9): Duplicate identifier 'invalid'. (2300)
typings/main/ambient/dragula/dragula.d.ts (15,9): Duplicate identifier 'direction'. (2300)
typings/main/ambient/dragula/dragula.d.ts (16,9): Duplicate identifier 'copy'. (2300)
typings/main/ambient/dragula/dragula.d.ts (17,9): Duplicate identifier 'revertOnSpill'. (2300)
typings/main/ambient/dragula/dragula.d.ts (18,9): Duplicate identifier 'removeOnSpill'. (2300)
typings/main/ambient/dragula/dragula.d.ts (19,9): Duplicate identifier 'delay'. (2300)
typings/main/ambient/dragula/dragula.d.ts (20,9): Duplicate identifier 'mirrorContainer'. (2300)
typings/main/ambient/dragula/dragula.d.ts (24,9): Duplicate identifier 'containers'. (2300)
typings/main/ambient/dragula/dragula.d.ts (25,9): Duplicate identifier 'dragging'. (2300)
typings/main/ambient/dragula/dragula.d.ts (47,5): Duplicate identifier 'export='. (2300)
```

**Comment by valorkin** [comment]
aha, ok got it
don't bother with peer dependencies
I will update it and drop a bit more instructions

**Comment by mburger81** [comment]
@valorkin okay thx let us know when we can try it again

**Comment by valorkin** [comment]
to be honest this tool/* stuff should be even part of npm package

**Comment by valorkin** [comment]
@denodaeus try to 
```bash
npm install --save dragula ng2-dragula@beta
npm install --save bootstrap@3.3.6 es6-promise@3.0.2 reflect-metadata@0.1.2 rxjs@5.0.0-beta.0 zone.js@0.5.10
```
don't bother about `UNMET PEER DEPENDENCY zone.js@0.5.11` use `.10` 
11+ versions has typings issues

**Comment by denodaeus** [comment]
```shell
[1] Serving "/Users/bsmith/Development/git/test/test-ui" at http://localhost:8080 (http://127.0.0.1:8080)
[0] app/work-board/work-board.component.ts(20,41): error TS2307: Cannot find module 'ng2-dragula'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(9,5): error TS2300: Duplicate identifier 'done'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(10,5): error TS2300: Duplicate identifier 'value'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(475,11): error TS2300: Duplicate identifier 'Promise'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(552,13): error TS2300: Duplicate identifier 'Promise'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(561,5): error TS2300: Duplicate identifier 'size'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(570,5): error TS2300: Duplicate identifier 'prototype'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(581,5): error TS2300: Duplicate identifier 'size'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(590,5): error TS2300: Duplicate identifier 'prototype'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(605,5): error TS2300: Duplicate identifier 'prototype'.
[0] node_modules/angular2/typings/es6-shim/es6-shim.d.ts(619,5): error TS2300: Duplicate identifier 'prototype'.
[0] typings/main/ambient/es6-collections/es6-collections.d.ts(24,5): error TS2300: Duplicate identifier 'done'.
[0] typings/main/ambient/es6-collections/es6-collections.d.ts(25,5): error TS2300: Duplicate identifier 'value'.
[0] typings/main/ambient/es6-collections/es6-collections.d.ts(48,5): error TS2300: Duplicate identifier 'size'.
[0] typings/main/ambient/es6-collections/es6-collections.d.ts(54,5): error TS2300: Duplicate identifier 'prototype'.
[0] typings/main/ambient/es6-collections/es6-collections.d.ts(68,5): error TS2300: Duplicate identifier 'size'.
[0] typings/main/ambient/es6-collections/es6-collections.d.ts(74,5): error TS2300: Duplicate identifier 'prototype'.
[0] typings/main/ambient/es6-collections/es6-collections.d.ts(90,5): error TS2300: Duplicate identifier 'prototype'.
[0] typings/main/ambient/es6-collections/es6-collections.d.ts(105,5): error TS2300: Duplicate identifier 'prototype'.
[0] typings/main/ambient/es6-promise/es6-promise.d.ts(14,15): error TS2300: Duplicate identifier 'Promise'.
[0] typings/main/ambient/es6-promise/es6-promise.d.ts(45,16): error TS2300: Duplicate identifier 'Promise'.
```

Looks like you're having some typings related issues with angular (they polute the type definitions space, especially if two versions of angular are installed via peer dependency resolution).

You might want to try upgrading this to angular2.0-beta.5+ (there is a beta6 coming that's resolves an rx.js issue, so might want to wait until that hits), but for now following the instructions you gave me, this is still not working.

**Comment by valorkin** [comment]
To keep you updated, I or @NathanWalker will update this repo to beta.6
and this problems should gone

**Comment by valorkin** [comment]
more or less
build process should be shifted

**Comment by NathanWalker** [comment]
I have been traveling on business this week; will be back the 17th. I will be able to update this lib to beta.6 at end of next week. @valorkin may get to it before then.

**Comment by valorkin** [comment]
nope, I am on travel until 22nd of Feb :)

**Comment by mburger81** [comment]
@NathanWalker if you can update it this week it would be great, i have an presentation on 22 of Feb and I would love it present my angular2 app with the drag&drop function. :)

thx

**Comment by NathanWalker** [comment]
I'll be updating this on Thursday :+1:

**Comment by mburger81** [comment]
@NathanWalker thank you so much! It would be great

**Comment by NathanWalker** [comment]
My Thursday will start in 8 hours so by end of day, I'll have it.

**Comment by mburger81** [comment]
I know ;) thx you

**Comment by NathanWalker** [comment]
@lanocturne 
@denodaeus 
@mburger81 
Please try the latest `1.1.0` which was just released:
https://www.npmjs.com/package/ng2-dragula

**Comment by denodaeus** [comment]
@NathanWalker:

No dependencies problems, but now it looks like the typescript compiler can't find the module without a .d.ts

```bash
[0] app/work-board/work-board.component.ts(24,41): error TS2307: Cannot find module 'ng2-dragula'.
[0] 10:44:07 AM - Compilation complete. Watching for file changes.
[1] File change detected /Users/bsmith/Development/git/qasymphony/kitsune-ui/app/boot.js
```

Here's my System js config:

```javascript
System.config({
  packages: {
    defaultJSExtensions: true,
    app: {
      format: 'register',
      defaultExtension: 'js'
    },
    '/ng2-table': { "defaultExtension" : "js" },
    '/ng2-dragula': { "defaultExtension" : "js" }
  },
  paths: {
    lodash: './node_modules/lodash/lodash.js',
    moment: './node_modules/moment/moment.js',
    'ng2-dragula': './node_modules/ng2-dragula',
    'ng2-table': '/node_modules/ng2-table'
  }
});   
```

I see that you have one, just not published to any repositories.  Do you know the best way to import this into my project?  I tried adding a relative path to my typings/browser.d.ts, like so:

```html
/// <reference path="../node_modules/ng2-dragula/ng2-dragula.d.ts" />
```

But after doing that, I get this:

```shell
[1] Serving "/Users/bsmith/Development/git/qasymphony/kitsune-ui" at http://localhost:8080 (http://127.0.0.1:8080)
[0] app/work-board/work-board.component.ts(24,41): error TS2307: Cannot find module 'ng2-dragula'.
[0] node_modules/ng2-dragula/src/app/directives/dragula.directive.ts(10,15): error TS2304: Cannot find name 'require'.
[0] node_modules/ng2-dragula/src/app/providers/dragula.provider.ts(1,15): error TS2304: Cannot find name 'require'.
```

Any thoughts?

Thanks

**Comment by denodaeus** [comment]
I see a project (from a different opened issue) that got this to work, but by copy-pasting the ng2-dragula code to be internal to the project (what I'm trying to avoid):

https://github.com/LombardInternational/document-merge-service

Also, no offense, but can you avoid closing issues until you confirm they're actually resolved by who opened them?  Thanks for your help.

**Comment by mburger81** [comment]
I still have problems, I'm using a angular2-webpack-starter project and upgradet it to the latest version after that i do this with output

npm install ng2-dragula --save

```
michi@zotacei730:~/software/workspace/web-client$ npm install ng2-dragula --save
npm WARN install Couldn't install optional dependency: Unsupported
lanthings-homeauto@0.0.1 /home/michi/software/workspace/web-client
├── UNMET PEER DEPENDENCY dragula@3.6.3
└── ng2-dragula@1.1.0 

npm WARN EPEERINVALID ng2-dragula@1.1.0 requires a peer of dragula@3.6.3 but none was installed.
```

now I have isntalled dragula ^1.1.0

after that I do an import in my component and add it to directives and viewProviders

```
import { Dragula, DragulaService } from 'ng2-dragula/ng2-dragula';
...
@Component({
    selector: 'app-dashboard',
    directives: [Dragula, ....],
    viewProviders: [DragulaService],
....
```

on run my app with
`npm start`
I got this errors

```
ERROR in ./~/ng2-dragula/src/app/directives/dragula.directive.ts
Module not found: Error: Cannot resolve module 'dragula' in /xxxx/node_modules/ng2-dragula/src/app/directives
 @ ./~/ng2-dragula/src/app/directives/dragula.directive.ts 12:14-32

ERROR in ./~/ng2-dragula/src/app/providers/dragula.provider.ts
Module not found: Error: Cannot resolve module 'dragula' in /xxxxxx/node_modules/ng2-dragula/src/app/providers
 @ ./~/ng2-dragula/src/app/providers/dragula.provider.ts 10:14-32
```

thx
Michael

**Comment by rigoleto** [comment]
@mburger81, run this: `npm install ng2-dragula@1.1.0 dragula@3.6.3 --save`

**Comment by rigoleto** [comment]
These TS errors have gone away completely for me  :+1:

**Comment by denodaeus** [comment]
I've gotten past by above issue by fixing the import statement (I do *not* understand why this works, except I guess the mapping in the system.js file under paths maps to a directory and not a file):

```javascript
import { Dragula, DragulaService } from 'ng2-dragula/ng2-dragula';
```

But now, I get the following problem when starting my app:

```shell
> kitsune-ui@0.0.1 go /Users/bsmith/Development/git/qasymphony/kitsune-ui
> concurrent "npm run tsc:w" "npm run serve"

[0]
[0] > test-ui@0.0.1 tsc:w /Users/bsmith/Development/git/qas/kitsune-ui
[0] > tsc -w
[0]
[1]
[1] > test-ui@0.0.1 serve /Users/bsmith/Development/git/qas/test-ui
[1] > live-server --host=localhost --port=8080 .
[1]
[1] Serving "/Users/bsmith/Development/git/qas/test-ui" at http://localhost:8080 (http://127.0.0.1:8080)
[0] node_modules/ng2-dragula/src/app/directives/dragula.directive.ts(10,15): error TS2304: Cannot find name 'require'.
[0] node_modules/ng2-dragula/src/app/providers/dragula.provider.ts(1,15): error TS2304: Cannot find name 'require'.
[0] 11:50:52 AM - Compilation complete. Watching for file changes.
[1] File change detected /Users/bsmith/Development/git/qas/test-ui/app/boot.js
[1] File change detected /Users/bsmith/Development/git/qas/test-ui/app/boot.js.map
```

I'm using System.js, and my index.html has no import for require.js, but I though this would be handled internally by the module and it would only export the correct JS object for me to use.

**Comment by denodaeus** [comment]
Installing a typing for require for my root project worked to fix that:

typings install --save --ambient require

At this point, with the system.js config like so:

```javascript
System.config({
  packages: {
    defaultJSExtensions: true,
    app: {
      format: 'register',
      defaultExtension: 'js'
    },
    map: {
      '/ng2-dragula': { defaultExtension: 'js' },
    }
  },
  paths: {
    lodash: './node_modules/lodash/lodash.js',
    moment: './node_modules/moment/moment.js',
    'ng2-dragula': './node_modules/ng2-dragula',
  }
});
```

Typescript finds the module, but when I actually go to use the imports in a component directive:

```javascript
@Component({
  selector: 'work-board-category',
  directives: [
    WorkItemComponent,
    Dragula
  ],
  viewProviders: [
    DragulaService
  ],
```

I am getting this error:

<img width="1568" alt="2016-02-18_1201" src="https://cloud.githubusercontent.com/assets/249286/13151268/71cf0402-d637-11e5-890d-ad9c4ed3172d.png">

I think what would be really helpful is if you could throw up a quick example project that shows using ng2-dragula as a external dependency, and not with using local file references.

**Comment by mburger81** [comment]
@rigoleto that works for me now I don't get any errors
but the drag&drop doesn't work a simple

```
      <div>
        <div [dragula]='"first-bag"'>aaaaaaaaaaaaaaaaaaaaaaaaaaaaa</div>
        <div [dragula]='"first-bag"'>bbbbbbbbbbbbbbbbbbbbbbbbbbbbb</div>
        <div [dragula]='"first-bag"'>ccccccccccccccccccccccccccccc</div>
        <div [dragula]='"first-bag"'>ddddddddddddddddddddddddddddd</div>
      </div>
```

does not do anything

**Comment by rigoleto** [comment]
@mburger81 
```html
<div [dragula]='"first-bag"'>
  <div>aaaaaaaaaaaaaaaaaaaaaaaaaaaaa</div>
  <div>bbbbbbbbbbbbbbbbbbbbbbbbbbbbb</div>
  <div>ccccccccccccccccccccccccccccc</div>
  <div>ddddddddddddddddddddddddddddd</div>
</div>
```

**Comment by mburger81** [comment]
@rigoleto o sorry, I'm an idiot and very tired!!!! 

thx you ... now for me anything is working!!!!

**Comment by NathanWalker** [comment]
@denodaeus If you are still having trouble, please open a new issue with the specific issue you are seeing now. Also if anyone else if having issues at this point, please post new issues and I'll consolidate what is posted.

Sorry if this got closed inadvertently, I usually just mention the issue in the commit, but places `closes` in front of it so it closed when the commit got pushed.

**Comment by denodaeus** [comment]
@NathanWalker acknowledged.

I was able to get this working after a long reddit discussion on the difficulties of using system.js with angular2.  I just switched my project to webpack and everything is now working the way I expect (in terms of importing and using the library).

Thanks again for your help.

**Comment by NathanWalker** [comment]
@denodaeus good to hear :+1:
